FROM rust:1.45 as builder
WORKDIR /usr/src/rust-playground
COPY . .
RUN cargo install --path .

FROM alpine:latest
#RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/rust-playground /usr/local/bin/rust-playground
EXPOSE 3030
CMD ["rust-playground"]